### ISSUE TITLE
Trying to make the code more rust idomatic

### ISSUE THREAD

**Issue by jaytaph** [gosub-browser/gosub-engine#10]
Since my lack of knowledge on Rust, a lot of code is probably not idomatic. For instance, I seem to use a lot of `unwrap()`, which I found out is not the best way to make things more robust.

Since the codebase is small, we should try and see where we can fix these things.

**Comment by TheFanatr** [comment]
Hey! Maybe adding a code style enforcement pipeline via a linter, or just specifically [`rustfmt`](//rust-lang/rustfmt), might help with this. 👍

**Comment by jaytaph** [comment]
We currently run `cargo fmt` as a build step in the CI. Is this what you mean with `rustfmt` (i'm not very experiences with rust yet).

**Comment by emwalker** [comment]
@TheFanatr see the recent [Makefile](https://github.com/jaytaph/gosub-browser/blob/b56f51c1c485e69034ff5d54c1d0d88909ea0a5c/Makefile#L22-L30). 

Looks like https://github.com/rust-lang/rustfmt and `cargo fmt` [are the same thing](https://github.com/rust-lang/rustfmt#on-the-stable-toolchain).

**Comment by emwalker** [comment]
>  For instance, I seem to use a lot of unwrap(), which I found out is not the best way to make things more robust.

Related comment [here](https://github.com/jaytaph/gosub-browser/issues/44#issuecomment-1741756365).  I can look into this if it sounds like an improvement.

**Comment by jaytaph** [comment]
We're doing better now. But this will be a ongoing task.

**Comment by Sharktheone** [comment]
Maybe we can also use something like https://github.com/dtolnay/no-panic, but I'm not sure, how that looks like with dependencies that might panic

**Comment by jaytaph** [comment]
We could enforce that gosub crates do not panic, but always return errors back to the caller for instance?

**Comment by Sharktheone** [comment]
Yes, or show it to the user. I guess, we should make another issue for that
