### ISSUE TITLE
change file structure for node related files

### ISSUE THREAD

**Issue by lucalewin** [gosub-browser/gosub-engine#120]
I've noticed that there 4 different files starting with `node` the `html5_parser` module. This seems like it could be grouped into a folder called `node` or `nodes`.

I would suggest something like this:
```text
html5_parser/
├─ .../
├─ node/
│  ├─ data/
│  │  ├─ comment.rs
│  │  ├─ document.rs
│  │  ├─ element.rs
│  │  ├─ mod.rs
│  │  ├─ text.rs
│  ├─ arena.rs
│  ├─ mod.rs
```

If you want I could create a pr for this?

**Comment by Kiyoshika** [comment]
I introduced these files in one of my PRs. Im good with this structure, although note that we moved away from the mod.rs convention (see #102). I can’t remember if I faced a challenge with this or if I just didn’t try.

If you can make it work, then sounds good to me

**Comment by Kiyoshika** [comment]
Oh, I was only paying attention to the node_data files, this is for all node related files. Either way, if we can support a better structure with the newer convention we’re using, then that’ll probably be good

**Comment by lucalewin** [comment]
so something like this?

```text
html5_parser/
├─ .../
├─ node/
│  ├─ data/
│  │  ├─ comment.rs
│  │  ├─ document.rs
│  │  ├─ element.rs
│  │  ├─ text.rs
│  ├─ arena.rs
│  ├─ data.rs
├─node.rs
```

**Comment by Kiyoshika** [comment]
Yeah, something like that would likely work. Although since this is also changing the structure of all the node files, I'd also request review from @jaytaph && @emwalker in your PR
