### ISSUE TITLE
Move plotting of trees into a separate tree plotter structure

### ISSUE THREAD

**Issue by jaytaph** [gosub-browser/gosub-engine#146]
At the moment there is code inside the nodes / arena that displays node trees. This is not the place for this.
Instead, we should have a separate tree plotter that gets a document tree as input, and can output the tree itself. This separates the output from the functionality.

**Comment by dibashthapa** [comment]
@jaytaph I want to work on this.

**Comment by jaytaph** [comment]
Go for it! :)

**Comment by jaytaph** [comment]
I think this is not needed anymore
