### ISSUE TITLE
research spidermonkey / mozjs-rust

### ISSUE THREAD

**Issue by jaytaph** [gosub-browser/gosub-engine#255]
- [X] can mozjs be easily compiled into the current gosub project
- [X] do a simple eval of inline code
- [ ] load a js file and execute it
- [ ] create a simple "document" object that has a "write" function, that will output any content to the output
- [ ] catch errors (incl syntax errors) from the javascript engine so we can use them in gosub

**Comment by blaumeise20** [comment]
I still think we should use JavaScriptCore ~~because Apple good~~ 😉

No actually, I read that JSC is supposed to be the fastest up to date JavaScript engine.

Random thought: what about making our own completely from scratch?

**Comment by Kiyoshika** [comment]
> Random thought: what about making our own completely from scratch?

This is something I'd like to experiment with eventually, but I imagine a JS engine is one of the longest components to make (the HTML parser alone took around 2-3 months to get into a good shape) so for now using a drop in engine just to get things working should be good enough

But it would be cool if we had all of our own "Gosub" components (HTML, CSS, JS, etc)

**Comment by emwalker** [comment]
I do not have any special love for or attachment to SpiderMonkey, personally.  I probably would have deprioritized it when the build issues became apparent.

**Comment by Sharktheone** [comment]
We can probably close this issue now, since we sticked with v8 for now. 
Also, I managed to complete all the tasks mentioned here.
