### ISSUE TITLE
Add note about `AUTHORS` file in contribution guidelines

### ISSUE THREAD

**Issue by Kiyoshika** [gosub-browser/gosub-engine#308]
As we're still fixing some issues with the github action related to the authors file, can add a note about including your name/email in the `AUTHORS` file when making a PR in the contribution guidelines

**Comment by jaytaph** [comment]
@Kiyoshika are you ok to pick this up?

**Comment by jaytaph** [comment]
The authors check is fixed, so this is not needed anymore
