### ISSUE TITLE
[CI] It doesn't run all tests anymore

### ISSUE THREAD

**Issue by Sharktheone** [gosub-browser/gosub-engine#390]
Since #379 CI doesn't run all tests, only the tree construction and tokenizer ones
For example [here](https://github.com/gosub-browser/gosub-engine/actions/runs/8045061843/job/21969685135?pr=383#step:8:450)

Many tests also don't compile anymore, because the use statements aren't working anymore. I noticed this where I added more tests for V8 (#383)

**Comment by jaytaph** [comment]
I had a similar issue.   One of the modifications made that one of the test didn't pass, but it didn't show up in the CI..
