### ISSUE TITLE
Getting the adoption agency algorithm to work properly

### ISSUE THREAD

**Issue by jaytaph** [gosub-browser/gosub-engine#43]
There seem to be issues with the current implementation of the adoption agency algorithm. I've implemented this with the help of [https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm](https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm).

Not all steps are implemented yet (4.19 and 4.14), but there is probably more missing and incorrect. 

[https://github.com/jaytaph/gosub-browser/blob/parser/src/html5_parser/parser/adoption_agency.rs](https://github.com/jaytaph/gosub-browser/blob/parser/src/html5_parser/parser/adoption_agency.rs)

**Comment by Ana17122** [comment]
Thank you very much for your information. Your post is very helpful. 
[True Life Info](https://www.truelifeinfo.com).

**Comment by jaytaph** [comment]
The current implementation is almost ready.. There are a few misformatted html streams that it can handle, but one of the major one (`<a><p>X<a>Y</a>Z</p></a>`) still forms a challenge.

**Comment by jaytaph** [comment]
Currently, the test 23 is passing! There are some tests that arent done correctly, and im just testing one of the parser test files, but it seems that we are getting somwwhere.

**Comment by jaytaph** [comment]
Tests are passing. It looks correctly implemented

**Comment by Ana17122** [comment]
[People are really talented](https://anannabeautytips.blogspot.com). I admire talented people.
