### ISSUE TITLE
Add ability to pass a local file into `gosub-browser` executable

### ISSUE THREAD

**Issue by Kiyoshika** [gosub-browser/gosub-engine#81]
Right now we can pass a URL, but I think it'll be useful for testing if we can do something like:
`gosub-browser file:///path/to/myfile.html`

We already have an ability to read a file with `InputStream` so I think this should be relatively easy.

**Comment by jaytaph** [comment]
That should indeed be easy enough to do.

However, I think we might need to change the name of the binary for the moment, as this might cause people to think it is an actual browser. Right now, it's more of a parse-html-like app.

I think we should update the readme as well to reflect the current status a bit better. We don't want to get anyone's hope up that we somehow have a chrome-alternative ready to run.

**Comment by Kiyoshika** [comment]
That makes sense. We can just rename it to `gosub-parse` or something along those lines for the time being

**Comment by psuedomoth** [comment]
Hey, I'd like to work on this.

**Comment by Kiyoshika** [comment]
> Hey, I'd like to work on this.

Great! To my knowledge no one has started on this, I can assign it to you

**Comment by Kiyoshika** [comment]
@psuedomoth also FYI since you're a first-time contributor, we require verified commits in this project, setting up your git to sign commits now will be a lot easier than trying to edit your history and verifying - https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
