### ISSUE TITLE
Specifying the MSRV

### ISSUE THREAD

**Issue by auronandace** [gosub-browser/gosub-engine#91]
I was just wondering what is the policy on the Minimum Supported Rust Version for this project? Is the plan just to use the latest stable release or would you rather be conservative for the sake of those using older toolchains? Would you welcome fixing `clippy::pedantic` lints in PRs (which ones apply would depend on the MSRV)?

The `Cargo.toml` file doesn't seem to have a `rust-version` field in it.

**Comment by jaytaph** [comment]
I think for now we can safely assume we only support the latest stable. @emwalker any objections on this, or can there be reasons we should support older/newer versions as well?

**Comment by auronandace** [comment]
For me personally the latest stable release is fine as I manage rust through rustup. I suspect a lot of people do the same too.

Supporting latest stable version only:
- Pro: Access to the latest stable features.
- Con: No access to beta/nightly features. (I'd consider this a pro since I prefer stability)
- Con: Only those with the latest stable release can try out the project.
- Con: Need to bump MSRV every new rust release.

Supporting older stable versions:
- Pro: Some install rust through a distibution package manager on linux. Not all distributions will have the latest version. Debian is probably one of the most popular that tends to lag behind. This allows you to have the widest potential install base possible.
- Con: You cannot use features from new stable versions above the MSRV. Might force you to adopt certain patterns when coding.
- Con: Bumping the MSRV will require considering which distros you want to support, effectively letting their package and support timespan dictate your MSRV policy.

Supporting newer (betas/nightlies):
- Pro: Access to newer features earlier.
- Con: If beta/nightly features are used then people will require a nightly toolchain. This will likely be the worst option regarding potential install base.
- Con: Not all nightly features are guaranteed to become stable and may be removed. Would be tricky relying on such features only to later have them not work out and require refactoring the code to adjust.

Some projects take a pragmatic middle ground between latest stable release and much older toolchain: They stick to stable toolchain only but figure out the oldest based on whatever feature they need in the project and set the MSRV accordingly. It does mean when you want a newer feature you'll need to bump the MSRV though, which in turn may cut off some users on older toolchains.

In the end it is a balancing act based on the project's priorities. Whatever strategy you choose it is always good to have the MSRV set so people know the limits.

I hope I explained the pros and cons well enough. Given the age of the project and pace of development I think latest stable release is probably the most suitable but that is just my opinion.

**Comment by jaytaph** [comment]
Distrowatch has a large list of distributions with package release info: https://distrowatch.com/dwres.php?resource=package-in-distro&pkg=rust

This shows:

| distro  | version    | rust            |
|---------|------------|-----------------|
| Ubuntu  | 20.04      | 1.41.0 / 1.66.1 |
| Ubuntu  | 22.04      | 1.58.1 / 1.66.1 |
| Ubuntu  | 23.04      | 1.67.1          |
| Ubuntu  | 23.10      | 1.71.1          |
| Debian  | unstable   | 1.70.0          |
| Debian  | testing    | 1.70.0          |
| Debian  | 12: 1.63.0 |                 |
| RHEL    | 9.2        | 1.66.1          |
| RHEL    | 8.7        | 1.62.1          |
| FreeBSD | 14-CURRENT | 1.72.0          |
| FreeBSD | 13-STABLE  | 1.72.0          |
| FreeBSD | 13.1       | 1.59.0          |

**Comment by jaytaph** [comment]
We could have a build matrix in the ci to check against different rust versions. That might help us, as the stable version is currently 1.72, and a lot of distro's are behind on 1.62+. We should not commit to supporting lower versions, but unless there is a valid reason to remove support, i think we should be able to handle 1.62/66 to stable?

**Comment by emwalker** [comment]
My understanding is that those versions are ones that come preinstalled with various Linux distributions.  A lot of rust developers will ignore that version of Rust prepackaged on their system and instead install `rustup` and use `rustup` to install latest stable, nightly, and older versions.  So we might be able to more or less ignore the  preinstalled versions for now, since you can use `rustup` to install those versions and other ones once you're set up.

Keeping a CI matrix of version comparability might be interesting.  What I'm curious about is how many developers that want to work on this project are unable for some reason to install `rustup`.  The number might be small or zero.

**Comment by jaytaph** [comment]
I'd reckon this is not a repository for rust beginners to experiment with, and that our toolchain will become more complex in the future, so having rustup as a "prerequisite" is fine by me.

**Comment by emwalker** [comment]
@auronandace the thinking is to specify "latest stable" as the MSRV, with the possibility of switching to nightly at some point, and to require `rustup` as a development dependency for the time being.  Does this approach make sense to you?  Would you be willing to submit a pull request?  If not, I might be able to do so at some point.

**Comment by auronandace** [comment]
Yes, that sounds reasonable to me. Most people use `rustup` anyway and this project is fast moving.

You can to the PR since I've never done any commit signing before.

Should just be adding the following to Cargo.toml: `rust-version = "1.73"`

**Comment by emwalker** [comment]
Pull request opened: https://github.com/gosub-browser/gosub-engine/pull/106.
